### ISSUE TITLE
tsearchn() returns NA for some points within triangle

### ISSUE THREAD

**Issue by jlause** [davidcsterratt/geometry#39] opened 2019-08-08 16:04 UTC
Hey David!

**tl;dnr**: `tsearchn()` seems to fail (=return NA) for some points that lie within the triangulation. Some changes to the input data points can fix the problem in unpredictable ways.

While using the `retistruct` package, I came across a weird error. When projecting datapoints from the flat 2D space to the spherical space (which is done by `tsearchn()` from `geometry`), it reported that some datapoints where excluded because they are outwith the outline.

A bit of digging and plotting revealed that the datapoints are within the outline. I narrowed the problem down to the `tsearchn()`, within which I could not follow the error further as it seems to call compiled C code at some point.

I found this error on my system with Ubuntu 16.04, R 3.4.1 and `geometry_0.4.2`. `geometry_0.4.0` gave the same error). The error persists on Windows 10 with R 3.6.1.

Here is some minimal example code that demonstrates the weird pattern around this bug:

```
#vertices
P = rbind(
    c(373.8112, 4673.726), #31
    c(222.9705, 4280.085), #32
    c(291.0508, 4476.996), #42
    c(553.4783, 4523.605), #43
    c(222.6388, 4023.920), #44
    c(445.2401, 4370.940), #48
    c(81.54986, 4125.393)) #61
I found this error on my system with Ubuntu 16.04, R 3.4.1 and `geometry_0.4.2`. `geometry_0.4.0` gave the same error). The error persists on Windows 10 with R 3.6.1.

#triangulation
T = rbind(
    c(3,   2,   6),
    c(5,   2,   7),
    c(4,   1,   3))

#data
data = rbind(
    c(221.6, 4171.8),
    c(250.4, 4311.8),
    c(496.6, 4516.2),
    c(254.0, 4294.8),
    c(199.4, 4072.6))

#plot vertices
plot(P)
#plot triangles
lines(P[c(3,2,6,3),])
lines(P[c(5,2,7,5),])
lines(P[c(4,1,3,4),])
#plot datapoints
points(data,pc=4)

library(geometry)
#returns NA for datapoints 3 and 5
tsearchn(P,T,data)
#plot NA points in red
points(data[is.na(tsearchn(P,T,data)$idx),],col='red')
```

The output of this is as follows:

```
$idx
[1]  2  1 NA  1 NA

$p
           [,1]      [,2]        [,3]
[1,] 0,41745497 0,5738332 0,008711813
[2,] 0,12125981 0,7924752 0,086265040
[3,]         NA        NA          NA
[4,] 0,01201408 0,8520628 0,135923121
[5,]         NA        NA          NA
```
This indicates that the 3rd and 5th point should be outwith the triangulation. They are marked red in the following plot, showing that both are in fact within the triangulation:

![image](https://user-images.githubusercontent.com/34481813/62717913-0e5ba280-ba05-11e9-8fd7-18a9ae2fd38a.png)

Rounding seems to fix the problem:

```
> tsearchn(P,T,round(data))
$idx
[1] 2 1 3 1 2

$p
           [,1]       [,2]        [,3]
[1,] 0,41838357 0,57573524 0,005881194
[2,] 0,12340967 0,79278340 0,083806929
[3,] 0,78058223 0,01332711 0,206090659
[4,] 0,01319694 0,85124225 0,135560817
[5,] 0,70705042 0,12511007 0,167839513
```

In a weird coincidence, I discovered that a change to the 5th input datapoint (changing only it's y coordinate) can fix the problem for the 3rd input datapoint, while the output for the 5th is still NA:

```
#modifying datapoint 5's Y coordinate fixes problem for datapoint 3
data_dp5y_changed = rbind(
  c(221.6, 4171.8),
  c(250.4, 4311.8),
  c(496.6, 4516.2),
  c(254.0, 4294.8),
  c(199.4, 4072.0)) #note that only the Y coordinate of datapoint 5 was changed
#returns NA for datapoint 5, but datapoint 3 is suddenly not returning NA anymore
tsearchn(P,T,data_dp5y_changed)
```
Output:
```
$idx
[1]  2  1  3  1 NA

$p
           [,1]      [,2]        [,3]
[1,] 0,41745497 0,5738332 0,008711813
[2,] 0,12125981 0,7924752 0,086265040
[3,] 0,77858842 0,0148161 0,206595473
[4,] 0,01201408 0,8520628 0,135923121
[5,]         NA        NA          NA
```

I'd be very grateful if you have time to look into this (or point me to any error I made). I can provide more details if needed. Thanks in advance!

Jan.

Full example code:
[minimal_example_github.txt](https://github.com/davidcsterratt/geometry/files/3482634/minimal_example_github.txt)

**Comment by davidcsterratt** [comment] 2019-08-15 16:48
Thanks for the very helpful report and sorry for the delay in replying to it. I've isolated the method to tsearch, and in particular the quadtree alogirithm which is used by default. Compare
``` 
## quadtree method
> tsearch(P[,1], P[,2],T ,data[,1], data[,2])
[1]  2  1 NA  1 NA
## orig method
> tsearch(P[,1], P[,2],T ,data[,1], data[,2], method="orig")
[1] 2 1 3 1 2
```
The quadtree method was contributed by @Jean-Romain , and is much faster, which is why it's the default. I'll take a quick look at it to see if I can see why it seems to be failing; otherwise I'm relying on @Jean-Romain or we'll have to revert to the slow method...

**Comment by Jean-Romain** [comment] 2019-08-15 17:09
I will check that.

**Comment by davidcsterratt** [comment] 2019-08-15 17:25
Many thanks! With a bit of printf debugging, I've localised the bug (I think) to `tree->rect_lookup(xcenter, ycenter, half_width + eps, half_height + eps, points);` in `Rtsearch.cpp` but I'd have to work hard to understand things after that point.

**Comment by Jean-Romain** [comment] 2019-08-15 17:36
My guess is that it corresponds to points that lies exactly on the edges of the quadtree +/- epsilon.

**Comment by jlause** [comment] 2019-08-16 10:18
Thanks for your replies!

I tried to install the latest version geometry package from the master branch (after the pull request of jean-romain was merged, using `devtools::install_github("davidcsterratt/geometry", subdir="pkg")`), but that did not fix it for me.

As a quick temporary fix within the retistruct context, can I simply replace 

`tsearchn(P,T,data)` 
with 
`tsearch(P[,1], P[,2],T ,data[,1], data[,2], method="orig",bary = TRUE)`?

For my minimal example, this does the job :)

**Comment by jlause** [comment] 2019-08-16 12:16
Sorry for the confusion, I must have messed something up with the installation of the fixed geometry version - now my minimal example produces the correct result.

thanks a lot!

**Comment by davidcsterratt** [comment] 2019-08-16 13:05
No worries, I think I must have committed the fix just after you tried.

**Comment by jlause** [comment] 2019-08-16 13:19
Yes, maybe I was too quick :)

By chance, I found that one problem from my minimal example seems to remain - can you reproduce that as well?

```
library(geometry)
#this now works fine
tsearchn(P,T,data)

#but modifying datapoint 5's Y coordinate reintroduces NAs
data_dp5y_changed = rbind(
  c(221.6, 4171.8),
  c(250.4, 4311.8),
  c(496.6, 4516.2),
  c(254.0, 4294.8),
  c(199.4, 4072.0)) #note that only the Y coordinate of datapoint 5 was changed

#returns NA for datapoint 5
tsearchn(P,T,data_dp5y_changed)
```
Output:
```
> tsearchn(P,T,data_dp5y_changed)
$idx
[1]  2  1  3  1 NA

$p
           [,1]      [,2]        [,3]
[1,] 0,41745497 0,5738332 0,008711813
[2,] 0,12125981 0,7924752 0,086265040
[3,] 0,77858842 0,0148161 0,206595473
[4,] 0,01201408 0,8520628 0,135923121
[5,]         NA        NA          NA
```
Plot:
```
#plot modified datapoint 5 in red to show it is still in the triangulation..
points(data_dp5y_changed[is.na(tsearchn(P,T,data_dp5y_changed)$idx),1],data_dp5y_changed[is.na(tsearchn(P,T,data_dp5y_changed)$idx),2],pc=5,col='red')

```
![image](https://user-images.githubusercontent.com/34481813/63169860-1f756680-c038-11e9-92a5-af9fcf625143.png)

Updated minimal example code:
[minimal_example_github.txt](https://github.com/davidcsterratt/geometry/files/3509743/minimal_example_github.txt)

**Comment by davidcsterratt** [comment] 2019-08-16 15:19
Yes, I can reproduce this: @Jean-Romain, could you take another look please?

**Comment by davidcsterratt** [comment] 2019-08-16 15:59
Actually, I think I need to understand this myself. Putting this in QuadTree.cpp is instructive:
```
 if (!tree->insert(p)) {
      error("Failed to insert point into QuadTree");
    }
```

**Comment by davidcsterratt** [comment] 2019-08-16 16:08
Think I have a fix; will post shortly.

**Comment by Jean-Romain** [comment] 2019-08-16 18:35
Sounds good I will study this more in depth on Monday. I will check if adding `eps` in the constructor as you did does not have a unexpected side effect.

**Comment by davidcsterratt** [comment] 2019-08-19 09:22
Please do! I had a couple of other thoughts over the weekend:
* Are there other points in the code where we could throw errors if a function fails? I like the idea of an error being thrown if there's a problem
* The absolute `eps` mechanism might fail if the numbers are very large, such that `eps` is smaller than the largest number multiplied by ~1E-15, i.e. the significand precision https://en.wikipedia.org/wiki/Double-precision_floating-point_format.

**Comment by Jean-Romain** [comment] 2019-08-19 10:22
1. I do agree and I will add similar tests in my own code
2. In other packages (e.g. [deldir](https://github.com/cran/deldir/blob/master/R/deldir.R)), `eps` is a parameter of the function. When I modified the `pointInTriangle` function we got some troubles with floating precision. There is already  a parameter `esp` that can be exposed to the user

https://github.com/davidcsterratt/geometry/blob/67c74c952c1eb5f29109feb5f8ea70086325ebce/pkg/src/Rtsearch.cpp#L59

**Comment by Jean-Romain** [comment] 2019-08-19 15:08
So I thought about it. Here my conclusions:

Your fix is good because the error reported here can only arise for points that belong on the outer edge of the quadtree. Indeed an error at the edge cannot be compensated by another error (see image bellow).

![quadtree](https://user-images.githubusercontent.com/3872279/63275605-d3ad0200-c26f-11e9-8491-f0005b5feee5.png)

In the reproducible examples the two errors are both for points that belong on the outer edge.

```r
data = rbind(
  c(221.6, 4171.8),
  c(250.4, 4311.8),
  c(496.6, 4516.2),
  c(254.0, 4294.8),
  c(199.4, 4072.6))

#plot vertices
plot(P, asp=1)
x = mean(c(min(data[,1]), max(data[,1])))
y = mean(c(min(data[,2]), max(data[,2])))
r = max(max(data[,1])-min(data[,1]),max(data[,2])-min(data[,2]))/2
rect(x-r,y-r,x+r,y+r, border = "red")

#plot triangles
lines(P[c(3,2,6,3),])
lines(P[c(5,2,7,5),])
lines(P[c(4,1,3,4),])
#plot datapoints
points(data,pc=4)
```

![Rplot06](https://user-images.githubusercontent.com/3872279/63275926-65b50a80-c270-11e9-847d-5d10379ddda1.png)

Consequently my previous fix is not useful. Only the buffer at the top level is useful. You can remove 

https://github.com/davidcsterratt/geometry/blob/67c74c952c1eb5f29109feb5f8ea70086325ebce/pkg/src/QuadTree.cpp#L156

and `+ eps`

https://github.com/davidcsterratt/geometry/blob/67c74c952c1eb5f29109feb5f8ea70086325ebce/pkg/src/QuadTree.cpp#L159

**Comment by davidcsterratt** [comment] 2019-08-21 14:37
Pull request accepted. Geometry v0.4.3 is on its way to CRAN.

**Closed by davidcsterratt** 2019-08-21 14:37 UTC
Labels: bug

**Comment by jlause** [comment] 2019-08-21 14:59
Great, thanks a lot!
